Add Custom User
swsnu/swpp2021-team10 pull request #19
Opened 2021-11-05 09:15 UTC by veldic

Custom user 추가했습니다.
PR merge 이후 각자 db 초기화가 필요할 것 같습니다.

2021-11-05 17:45 UTC, dooly9931 commented
backend/connectoon/user/managers.py에서 29줄 쯤에 
extra_fields.setdefault('is_staff', True)를 뺀 것 같은데 admin 페이지에 로그인 잘 되나요?

2021-11-06 05:37 UTC, dooly9931 requested changes
그냥 comment에도 달았지만 backend/connectoon/user/managers.py에서extra_fields.setdefault('is_staff', True)는 없어도 괜찮은지 체크 한 번만 해주세요. 
backend/connectoon/user/managers.py랑 backend/user/connectoon/user/models.py에서 username이 없으면 예외로 처리되고, REQUIRED_FIELDS로 분류했는데 password에 대해서는 따로 해주지 않아도 없으면 예외로 처리돼서 하지 않은건가요?

2021-11-06 07:45 UTC, veldic commented
1. django admin에 필요한 것 같아서 추가했습니다.
2. password와 identifier (email)에 대해서는 필요하지 않다고 적혀있었습니다. 
![image](https://user-images.githubusercontent.com/50933769/140602220-a2db841f-c337-4a3e-8c2b-7018e907712d.png)

2021-11-06 07:59 UTC, dooly9931 approved these changes
좋습니당

2021-11-06 08:17 UTC, merged