Backend workID, work review구현
swsnu/swpp2021-team10 pull request #30
Opened 2021-11-06 18:59 UTC by hursuhyun

login로직이 필요한 workid/review를 제외하고 구현을 다 했습니다. 데이터가 아직 db에 없어서 db와의 상호작용은 확인 못하지만 테스트는 잘 통과합니다. 다만 login이 필요한 post work/id/review/는 로그인 로직이 없어 테스트 불가능 상태입니다.

2021-11-08 15:29 UTC, veldic requested changes

2021-11-08 15:29 UTC, veldic commented on backend/connectoon/work/views.py
> +        most_reviewed_works_json = json.dumps(list(most_reviewed_works))
이것도 위에 JSON 과 같은 질문입니당

2021-11-08 17:27 UTC, hursuhyun commented on backend/connectoon/work/views.py
> +        return JsonResponse(list(work), safe = False, status = 200)
![image](https://user-images.githubusercontent.com/38004175/140789331-ed62de30-9bee-407a-96b1-820b048b61a4.png)
여기는 그대로 다 넣으면 될 것 같습니다..!

2021-11-09 03:54 UTC, veldic commented on backend/connectoon/work/views.py
> +        return JsonResponse(list(work), safe = False, status = 200)
API 명시된대로 json이 다 출력되나요? 출력 결과가 필요할 것 같은데

2021-11-09 10:42 UTC, dooly9931 commented
works/main의 view 메서드에서 work 안에 completion 포함시켜주세요!

2021-11-09 10:51 UTC, hursuhyun commented on backend/connectoon/work/views.py
> +        return JsonResponse(list(work), safe = False, status = 200)
![image](https://user-images.githubusercontent.com/38004175/140911080-f2af127e-ca8d-40d1-b545-4bb1b8cf7ca9.png)

이이렇게 나옵니다

2021-11-09 11:33 UTC, merged