Implemented Search and changed GenreTag component
swsnu/swpp2021-team10 pull request #32
Opened 2021-11-07 11:32 UTC by fjvxmap

태그 검색 윈도우 제외하고 Search 구현했고 경서한테 졸라서 경서가 만든 태그 컴포넌트 바꿨습니다. 백엔 아티스트 post, work post 및 get works/search 구현해두었고 package.json proxy 백엔 서버로 설정했습니다.

2021-11-07 11:46 UTC, fjvxmap commented
트래비스좀 고치겠습니다 잠시..

2021-11-07 11:47 UTC, hursuhyun commented on backend/connectoon/artist/views.py
> +        return HttpResponse(status=501)
파일 마지막엔 항상 newline추가해주세요!

2021-11-07 11:57 UTC, hursuhyun requested changes

2021-11-07 11:57 UTC, hursuhyun commented on backend/connectoon/artist/views.py
> +        return HttpResponse(status=501)
csrf_exempt없앨 수 있을까요?

2021-11-07 11:57 UTC, hursuhyun commented on backend/connectoon/work/views.py
> +        'plat': work.platform_id}, status=201)
이거 일일이 안해주고 `from django.forms.models import model_to_dict`이 친구 이용하면 더 쉽게 될겁니당

2021-11-07 11:57 UTC, hursuhyun commented on backend/connectoon/work/views.py
>  def work_search(request):  # TODO
관련 테스트 추가해주세요

2021-11-07 11:57 UTC, hursuhyun commented on frontend/connectoon/src/Containers/Search/Search.css
> +}
뉴라인!

2021-11-07 12:02 UTC, fjvxmap commented
엥 다 봐주시고 계셨네 그럼 저거대로 수정좀 하겠습니다

2021-11-07 12:03 UTC, fjvxmap commented on backend/connectoon/work/views.py
> +        'plat': work.platform_id}, status=201)
뭣..

2021-11-08 06:36 UTC, hursuhyun commented
@fjvxmap 트레비스 보면 에러 떠서 그거 수정 필요할 것 같습니다!

2021-11-08 06:41 UTC, fjvxmap commented
알겠습니다 잠시..

2021-11-08 07:12 UTC, hursuhyun commented on backend/connectoon/work/views.py
> +@csrf_exempt
없애면 실행 안되나요..?

2021-11-08 07:20 UTC, fjvxmap commented on backend/connectoon/work/views.py
> +@csrf_exempt
초기 크롤된 파일 올리때만 간편하게 쓰려고 했던건데 앞으로 db 만들때 csrf_exempt 달아서 만들고 도로 지워놓도록 하겠슴다

2021-11-08 12:13 UTC, hursuhyun commented on backend/connectoon/work/views.py
> +@csrf_exempt
넵! 음 그럼 work post는 깃에 안 올리는 방식이 나을 수도 있을 것 같습니다! 따로 저장해두고 깃에는 일단 올리지 말고 나중에 어드민 페이지 만들면 거기다 올리는 게 좋을 것 같기도 합니당

2021-11-08 14:27 UTC, fjvxmap commented on backend/connectoon/work/views.py
> +@csrf_exempt
확인하고 제 로컬로 빼두었습니다.

2021-11-08 14:31 UTC, fjvxmap commented on backend/connectoon/work/views.py
> +@csrf_exempt
push 직전에 확인하고 빼두었슴다

2021-11-08 15:11 UTC, hursuhyun commented on frontend/connectoon/src/Containers/TagSearchWindow/TagSearchWindow.js
> +    const selectedTag = storedTags.filter((x) => x.name === name)[0];
```suggestion
    const selectedTag = storedTags.find((x) => x.name === name);
```

2021-11-08 15:13 UTC, hursuhyun commented on frontend/connectoon/src/Containers/TagSearchWindow/TagSearchWindow.js
> +        tagName={x.name}
`key`가 필요합니다.
아래도 마찬가지

2021-11-08 15:18 UTC, fjvxmap commented on backend/connectoon/tag/models.py
> +    prior = models.BooleanField(default=False)
연관된 태그를 manytomany로 지정한 것입니다. 그냥 아이디를 리스트로 주면 되지 않나도 생각해봤는데 너무 편법같아서 저렇게 했슴다. prior은 검색창에 아무런 입력값이 없을 때 판타지, 로맨스 등등 상위 장르를 우선으로 표시하기 위해 해당 태그들에 true를 주기 위함입니다.

2021-11-08 15:18 UTC, fjvxmap commented on backend/connectoon/work/tests.py
> +        response = client.get('/works/search/?q=')
q가 비어있을때에 대한 브랜치가 존재하기 때문에 필요합니다.

2021-11-08 15:18 UTC, fjvxmap commented on backend/connectoon/work/views.py
> +                return_work_list[0].append({'title': work['title'], 'src': work['thumbnail_picture'],
재현이는말안드뤄

2021-11-08 15:19 UTC, fjvxmap commented on frontend/connectoon/src/Components/GenreTag/GenreTag.js
>  const GenreTag = (props) => {
음..? 저거 바꾼 기억은 없는데.. 상관은 없으나 다음 피알때 돌려놓겠습니다

2021-11-08 15:21 UTC, fjvxmap commented on frontend/connectoon/src/Components/GenreTag/GenreTag.js
> +  onDeleteTag: PropTypes.func,
왜 나는지는 잘 모르겠습니다

2021-11-08 15:22 UTC, fjvxmap commented on frontend/connectoon/src/Containers/TagSearchWindow/TagSearchWindow.js
> +    const selectedTag = storedTags.filter((x) => x.name === name)[0];
확인했습니다

2021-11-08 15:22 UTC, fjvxmap commented on frontend/connectoon/src/Containers/TagSearchWindow/TagSearchWindow.js
> +        tagName={x.name}
확인했습니다

2021-11-08 15:23 UTC, fjvxmap commented on frontend/connectoon/src/Components/GenreTag/GenreTag.js
> +      </div>}
확인했습니다

2021-11-08 15:27 UTC, hursuhyun commented on backend/connectoon/work/tests.py
> +        response = client.get('/works/search/?q=')
그 아랫줄에서 바로 response 업데이트 해주는데 필요한가요..?

2021-11-08 15:27 UTC, hursuhyun commented on frontend/connectoon/src/Components/GenreTag/GenreTag.js
>  const GenreTag = (props) => {
지금 돌려야 하지 않을까요..?

2021-11-08 15:27 UTC, fjvxmap commented on frontend/connectoon/src/Components/GenreTag/GenreTag.js
>  const GenreTag = (props) => {
아 Search - TagSearchWindow - GenreTag 순으로 주고받던 함수 관계를 TagSearchWindow - GenreTag 관계로 축소하면서 저렇게 되었습니다. 관련 내용 슬랙에 적어놓겠습니다.

2021-11-08 15:33 UTC, fjvxmap commented on backend/connectoon/work/tests.py
> +        response = client.get('/works/search/?q=')
리스폰스만 생성하면 q가 빈 경우의 if문을 테스트하게 되고, 바로 아랫줄에서 q가 유효한 값을 가질때를 테스트합니다.

2021-11-10 03:48 UTC, hursuhyun commented on backend/connectoon/tag/views.py
> +        return JsonResponse(return_tag_list, safe=False)
저희 원래 response가 이거였는데, related와 prior도 프론트에 넘겨주어야하나요?
![image](https://user-images.githubusercontent.com/38004175/141046351-fbc758eb-1f64-405e-958d-0d6c36a19dcd.png)

2021-11-10 05:01 UTC, fjvxmap commented on backend/connectoon/tag/views.py
> +        return JsonResponse(return_tag_list, safe=False)
아 이거 제가 수정해놓겠습니다.

2021-11-10 05:02 UTC, fjvxmap commented on backend/connectoon/tag/views.py
> +        return JsonResponse(return_tag_list, safe=False)
넘겨주어야 잘 돌아갑니다.

2021-11-10 05:20 UTC, dooly9931 commented
아조시 별건 아닌데 
const titleList = <WorkList className="ts-wl" class="title-search-work-list" subject="Title search result" workList={storedWorks[0]} workNumInRow={4} />;
const artistList = <WorkList className="as-wl" class="artist-search-work-list" subject="Artist search result" workList={storedWorks[1]} workNumInRow={4} />;
에서 class랑 className이랑 바꾸는거 어떤가요

2021-11-10 05:28 UTC, fjvxmap commented
수정했습니다

2021-11-10 06:46 UTC, merged