added backend to review
swsnu/swpp2021-team10 pull request #34
Opened 2021-11-08 20:52 UTC by hursuhyun

review 관련 api들 구현했습니다.
updated_at추가가 자동으로 안 되길래 model 수정했습니다.[link](https://docs.djangoproject.com/en/3.2/ref/models/fields/)

2021-11-09 12:55 UTC, veldic requested changes

2021-11-09 12:55 UTC, veldic commented on backend/connectoon/review/models.py
> +    updated_at = models.DateTimeField(default=timezone.now)
auto_now=True를 해줘야할 것 같습니다.
![image](https://user-images.githubusercontent.com/50933769/140927677-3f93e039-3500-426d-8c28-7f6ba23df050.png)

2021-11-09 12:55 UTC, veldic commented on backend/connectoon/review/tests.py
> +            email='dummy2@user.com', password='1234', username='dummy')
요거 제 PR(username 중복 제거) merge 되면 fail 뜰 것 같습니다. 수정해야할 것 같아요.

2021-11-10 03:36 UTC, hursuhyun commented on backend/connectoon/review/models.py
> +    updated_at = models.DateTimeField(default=timezone.now)
아 처음 데이터 넣을 때 auto_now가 안먹어서 저걸로 추가했는데, update를 할 때 되는지 다시 확인해보고 추가하겠습니다.

2021-11-12 19:57 UTC, hursuhyun commented on backend/connectoon/review/models.py
> +    updated_at = models.DateTimeField(default=timezone.now)
이거 그냥 제가 백에서 잘못 가져왔던 거라서 수정을 완전히 없앴습니다.

2021-11-12 19:57 UTC, hursuhyun commented
@veldic 커밋별로 보시면 보기 편하실거고, 저번에 백엔드 보셨으니 프론트만 보시면 될 겁니다!

2021-11-12 19:58 UTC, hursuhyun commented
![Uploading image.png…]()
프론트 결과입니다.

2021-11-13 01:58 UTC, dooly9931 reviewed
프엔 확인했습니다

2021-11-13 02:02 UTC, merged